PROJECTIONS=Gd:f;Gd:d;{TM}:d;Si:p
DIS_WIN_LO=11.0
DIS_WIN_HI=8.0
DIS_FROZ_LO=4.0
DIS_FROZ_HI=1.5
DIS_NUM_ITER=1000
DIS_CONV_TOL=1.0d-9
DIS_CONV_WINDOW=3
NUM_ITER=500
KMESH_PRIMITIVE=12 12 12
NBND_WINDOW=10
NBND_MARGIN=10
PAIRS={TM}-Si,{TM}-{TM}
DMAX=5.0
TMIN=0.02
QE_BIN=/mnt/wizardry/qe/build/bin
W90_BIN=
SRUN_OPTS=--mpi=pmix -n 48 -p trollen --exclusive
W90_SRUN_OPTS=-n 1 -p trollen
